name: kokorogaku
favicon: null
layout_spectrum: 0.99747
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#742334'
    - '#64bcc5'
    - '#9b822e'
    - '#ffffff'
    - '#b0dce2'
  brandStrength: 0.9375
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
